### ISSUE TITLE
请教怎么在ink里使用多说

### ISSUE THREAD

**Issue by ivangreat** [Nigh/blog_generator#1]
搞不定 key tile 和 url啊 。。。能帮帮吗 谢谢

**Comment by Nigh** [comment]
参见我写的主题[Saka](https://github.com/Nigh/Saka)

在article.html的最后，有多说组件的引用。

**Comment by ivangreat** [comment]
谢谢啊，问题解决了~~ PS 不好意思同时steal了你的主题，挺不错的~~ Thanks

**Comment by Nigh** [comment]
@ivangreat Saka主题本来就是公开共享的。
